In [50]:
import numpy as np
import pandas as pd

In [22]:
a1 = np.array([1,2,3]) #1D
a1

array([1, 2, 3])

In [23]:
a2 = np.array([[1,2,3],[4,5,6]]) #2D
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a3 = np.array([[[1,2,3.5],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) #3D
a3

array([[[ 1. ,  2. ,  3.5],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]],

       [[13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [29]:
a1.shape # numpy always consider single array as a column vector

(3,)

In [30]:
a2.shape

(2, 3)

In [31]:
a3.shape

(3, 2, 3)

In [44]:
a3[2,0,2]

15.0

In [45]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [48]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [49]:
type(a1)

numpy.ndarray

In [54]:
test = [2,3,1]
test

[2, 3, 1]

In [55]:
type(test)

list

In [111]:
np.random.seed(0) # random values generating by randint won't change after the first execution
np_array1 = np.random.randint(10,size=(2,3))
np_array1

array([[5, 0, 3],
       [3, 7, 9]])

In [112]:
np_array1[0,:]

array([5, 0, 3])

In [113]:
np_array1[1:3,1:3] # submatrix, m:n will extract elements from m to n-1

array([[7, 9]])

In [116]:
a2 + np_array1

array([[ 6,  2,  6],
       [ 7, 12, 15]])

In [118]:
5 // 2 # equals 2
5 / 2 # equals 2.5
5 % 2 # equals reminder

1

In [119]:
a2.T # transpose of a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
np.random.seed(1) # random values generating by randint won't change after the first execution
np_array2 = np.random.randint(10,size=(5,3))
np_array2

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [91]:
df = pd.DataFrame(np_array1, columns = ['x','y','z'])
df

x  y  z
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [82]:
np.ones((100,100))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [83]:
np.zeros((5,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [120]:
m_array = np.random.random(100000)
m_array

array([0.6235637 , 0.38438171, 0.29753461, ..., 0.90736856, 0.12361687,
       0.97674556])

In [121]:
m_array.size

100000

In [122]:
%timeit sum(m_array)  # time of execution

3.85 ms ± 74.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [128]:
timeit np.sum(m_array)

22.2 µs ± 211 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
